name: smart_home
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.7
  cupertino_icons: ^1.0.2
  dio: ^5.2.0+1
  loading_overlay:
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  shimmer_animation: ^2.1.0+1
  syncfusion_flutter_charts:
  syncfusion_flutter_datagrid:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CaviarDreams
      fonts:
        - asset: assets/fonts/CaviarDreams.ttf
